pipeline:
  name: main
  identifier: main
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: FranckboostOrg
        repoName: public
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhub
                    image: alpine
                    shell: Sh
                    command: |-
                      echo "Hello world"
                      echo "$SECRET_KEY"
                    envVariables:
                      SECRET_KEY: <+secrets.getValue('super_secret')>
