name: MyAction
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_SERVER_URL}/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}/code-scanning/alerts"
  #boost_security_semgrep:
  #  name: Semgrep scan
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Semgrep scan
  #      uses: boostsecurityio/boostsec-scanner-github@v4
  #      env:
  #        SEMGREP_RULES: auto p/rust p/typescript 
  #      with:
  #        api_token: ${{ secrets.BOOST_API_TOKEN }}
  #        registry_module: boostsecurityio/semgrep
  #        log_level: TRACE
