name: Build
on:
  push:
    branches: [ main ]
  
workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_SERVER_URL}/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}/code-scanning/alerts"
